# Generated by Django 4.2.1 on 2023-05-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0002_alter_contactinfo_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='message',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='name',
            new_name='firstName',
        ),
    ]
